// app-website/components/Header/NavLinks.vue
<template>
  <div class="nav-links-wrapper">
    <nuxt-link
      :class="{current: current === 'index'}"
      to="/">HOME</nuxt-link>
    <nuxt-link
      :class="{current: current === 'contact-us'}"
      to="/contact-us">CONTACT US</nuxt-link>
    <nuxt-link
      :class="{current: current === '404'}"
      to="/404">404 Page</nuxt-link>
    <a
      :class="{current: current === 'source'}"
      href="https://github.com/capricorncd/demos/tree/main/app-website" target="_blank">Source</a>
    <a
      :class="{current: current === 'github'}"
      href="https://github.com/capricorncd" target="_blank">Github</a>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        current: this.$route.name || 'index'
      }
    },
    watch: {
      $route (val) {
        this.current = val.name
      }
    }
  }
</script>

<style lang="scss">
  @import "assets/scss/constants";
  .nav-links-wrapper {
    position: absolute;
    top: 0;
    right: 65px;
    height: 58px;
    font-size: 0;
    a {
      display: inline-block;
      margin: 0 12px;
      color: #212121;
      font-size: 14px;
      line-height: 58px;
      &.current {
        color: $mainGreen;
        font-weight: 600;
      }
    }
  }
</style>

// react-next-app/Components/Header/NavLinks.tsx
/**
 * Created by Capricorncd.
 * https://github.com/capricorncd
 * Date: 2022/03/08 20:35:26 (GMT+0900)
 */
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../../styles/Header.module.scss'

const NavLinks = () => {
  const router = useRouter()
  const current =router.pathname.substring(1) || 'index'

  return (
    <div className={styles.nav}>
      <Link
        href="/">
        <a className={current === 'index' ? styles.current : ''}>HOME</a>
      </Link>
      <Link
        href="/contact">
        <a className={current === 'contact' ? styles.current : ''}>CONTACT US</a>
      </Link>
      <Link
        href="/404">
        <a className={current === '404' ? styles.current : ''}>404 Page</a>
      </Link>
      <a
        className={current === 'source' ? styles.current : ''}
        href="https://github.com/capricorncd/demos/tree/main/react-next-app"
        target="_blank"
        rel="noreferrer">Source</a>
      <a
        className={current === 'github' ? styles.current : ''}
        href="https://github.com/capricorncd"
        target="_blank"
        rel="noreferrer">Github</a>
    </div>
  )
}

export default NavLinks
